version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/services/
    
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
  AfterInstall:
    - location: scripts/afterinstall.sh
