version: 0.1

environment_variables:
   plaintext:
    GIT_USERNAME: "duobuilduser"
    GIT_EMAIL: "duobuilduser@duosoftware.com"
    GIT_PASSWORD: "DuoS1235"
    GO_VERSION: "1.7.4"
    GO: "/usr/local/go/bin"
    BuildOutPath: "$PWD"

phases:
  install:
    commands:
      - apt-get -y update && apt-get install -y python-software-properties

pre_build:
  commands:
    - rm -r "pkg" 
    - mkdir "bin" && mkdir "pkg" && mkdir "src" 
    - export PATH=$PATH:/usr/local/go/bin;
    - export GOPATH=$PWD;
    - git clone https://github.com/DuoSoftware/v6engine-deps $GOPATH/src

build:
  commands:
    - go build duoauth/duoauth.go
artifacts:
  files:
    - duoauth

