version: 0.1

environment_variables:
   plaintext:
    GIT_USERNAME: "duobuilduser"
    GIT_EMAIL: "duobuilduser@duosoftware.com"
    GIT_PASSWORD: "DuoS1235"
    GO_VERSION: "1.7.4"
    GO: "/usr/local/go/bin"
    BuildOutPath: "$PWD"

phases:
  install:
    commands:
      - apt-get -y update && apt-get install -y python-software-properties
      - echo Build started on `date`
      - mv v6engine duov6.com

build:
  commands:
    - echo Compiling the Go code...
    - go build duoauth/duoauth.go
    - go install
    
post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - duoauth

